server:
  port: 8084
spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue: # llave de configuración para conocer cómo se llama la cola
  serie:
    name: ColaSerie
  movie:
    name: ColaMovie

message: "Se levanta el microservicio catalog service"

#CONFIGURACIÓN DE EUREKA EN EL MICROSERVICIO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  
    instance:
      #hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      prefer-ip-address: false
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
  
  # CONFIGURACIÓN CORRESPONDIENTE A LA IMPLEMENTACIÓN DE FEIGN
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      movies: # se define el nombre de la instancia que se utilizará en el método donde se aplique circuitBreaker
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHlafOpenEnabled: true
  retry:
    instances:
      movies:
        maxAttemps: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError


  # EVALUAR SUMAR DEPENDENCIA PARA MEJORAR PREFORMANCE / Tolerancia a fallos
  #hystrix:
    #enabled: true

# EXTRA= SE PUEDE SUMAR LOGGING PARA VER CUALQUIER PROBLEMA RELATIVO AL BALANCEO
  #logging:
  #level:
    #com.netflix.loadbalancer: DEBUG
  


    