server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    default-filters: # Filtro por defecto de todas las requests realizadas al gateway
      - name: LogFilter
  locator:
    enabled: true
  default-filters:
    - FilterCustom
  routes:
    - id: id-catalog-service
      uri: lb://catalog-service
      predicates:
        - Path=/catalog/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


#si fuera con puerto definido en la ruta de catalog y movies
#spring:
  #application:
    #name: gateway
    #cloud:
       #default-filters: #Filtro por defecto de todas las requests realizadas al gateway
        #- name: LogFilter
      #locator:
        #enabled: true
      #default-filters:
        #- FilterCustom
      #routes:
        #- id: productRoute #identificador de la ruta
          #uri: http://localhost:8082 #URL donde se hará el redirect según el predicado definido
          #predicates: #Reglas de análisis del request
           # - Path=/movies/** #path de URL de request a considerar
        #- id: userRoute #identificador de la ruta
          #uri: http://localhost:8081 
          #predicates: 
            #- Path=/catalog/** 
          #filters: 
            #- AddRequestHeader=user-request-header, custom-user-request-header
            #- AddResponseHeader=user-response-header, custom-user-response-header 
      


    
    
